language: go
go:
  - 1.3
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libjack-dev libsndfile1-dev libsamplerate0-dev check
  - ./install-liblightning.bash
  - go get github.com/lightning/go
